# Generated by Django 4.2.3 on 2023-09-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paltar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('phone_number', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('messages', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo/'),
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_type', models.ManyToManyField(related_name='products', to='paltar.productmodel')),
            ],
            options={
                'verbose_name': 'product_type',
                'verbose_name_plural': 'products_types',
            },
        ),
    ]
